### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by knownasilya** [alexlafroscia/embroider-vite#3]
Any plans to add a readme so people can try this? Guess I could just look at the test app, but it always helps to have even a small description of what this is.

**Comment by alexlafroscia** [comment]
Not in particular; this repo is behind the PR that I'm working on in the Embroider repo itself

https://github.com/embroider-build/embroider/pull/759

I don't have a ton of time to invest into keeping both up-to-date these days, and have been waiting to make another push on the Embroider PR until their testing story has improved some and it's more clear how I would actually write tests for the Vite packager.

**Comment by knownasilya** [comment]
Sounds good.
